export const surahDetailsList = [
  { type: "مكية", verses: 7 }, { type: "مكية", verses: 286 }, { type: "مدنية", verses: 200 }, { type: "مدنية", verses: 176 },
  { type: "مدنية", verses: 120 }, { type: "مكية", verses: 165 }, { type: "مكية", verses: 206 }, { type: "مدنية", verses: 75 },
  { type: "مدنية", verses: 129 }, { type: "مكية", verses: 109 }, { type: "مكية", verses: 123 }, { type: "مكية", verses: 111 },
  { type: "مدنية", verses: 43 }, { type: "مكية", verses: 52 }, { type: "مكية", verses: 99 }, { type: "مكية", verses: 128 },
  { type: "مكية", verses: 111 }, { type: "مكية", verses: 110 }, { type: "مكية", verses: 98 }, { type: "مكية", verses: 135 },
  { type: "مكية", verses: 112 }, { type: "مدنية", verses: 78 }, { type: "مكية", verses: 118 }, { type: "مدنية", verses: 64 },
  { type: "مكية", verses: 77 }, { type: "مكية", verses: 227 }, { type: "مكية", verses: 93 }, { type: "مكية", verses: 88 },
  { type: "مكية", verses: 69 }, { type: "مكية", verses: 60 }, { type: "مكية", verses: 34 }, { type: "مكية", verses: 30 },
  { type: "مدنية", verses: 73 }, { type: "مكية", verses: 54 }, { type: "مكية", verses: 45 }, { type: "مكية", verses: 83 },
  { type: "مكية", verses: 182 }, { type: "مكية", verses: 88 }, { type: "مكية", verses: 75 }, { type: "مكية", verses: 85 },
  { type: "مكية", verses: 54 }, { type: "مكية", verses: 53 }, { type: "مكية", verses: 89 }, { type: "مكية", verses: 59 },
  { type: "مكية", verses: 37 }, { type: "مكية", verses: 35 }, { type: "مدنية", verses: 38 }, { type: "مدنية", verses: 29 },
  { type: "مدنية", verses: 18 }, { type: "مكية", verses: 45 }, { type: "مكية", verses: 60 }, { type: "مكية", verses: 49 },
  { type: "مكية", verses: 62 }, { type: "مكية", verses: 55 }, { type: "مدنية", verses: 78 }, { type: "مكية", verses: 96 },
  { type: "مدنية", verses: 29 }, { type: "مدنية", verses: 22 }, { type: "مدنية", verses: 24 }, { type: "مدنية", verses: 13 },
  { type: "مدنية", verses: 14 }, { type: "مدنية", verses: 11 }, { type: "مدنية", verses: 11 }, { type: "مدنية", verses: 18 },
  { type: "مدنية", verses: 12 }, { type: "مدنية", verses: 12 }, { type: "مكية", verses: 30 }, { type: "مكية", verses: 52 },
  { type: "مكية", verses: 52 }, { type: "مكية", verses: 44 }, { type: "مكية", verses: 28 }, { type: "مكية", verses: 28 },
  { type: "مكية", verses: 20 }, { type: "مكية", verses: 56 }, { type: "مكية", verses: 40 }, { type: "مدنية", verses: 31 },
  { type: "مكية", verses: 50 }, { type: "مكية", verses: 40 }, { type: "مكية", verses: 46 }, { type: "مكية", verses: 42 },
  { type: "مكية", verses: 29 }, { type: "مكية", verses: 19 }, { type: "مكية", verses: 36 }, { type: "مكية", verses: 25 },
  { type: "مكية", verses: 22 }, { type: "مكية", verses: 17 }, { type: "مكية", verses: 19 }, { type: "مكية", verses: 26 },
  { type: "مكية", verses: 30 }, { type: "مكية", verses: 20 }, { type: "مكية", verses: 15 }, { type: "مكية", verses: 21 },
  { type: "مكية", verses: 11 }, { type: "مكية", verses: 8 },  { type: "مكية", verses: 8 },  { type: "مكية", verses: 19 },
  { type: "مكية", verses: 5 },  { type: "مدنية", verses: 8 }, { type: "مدنية", verses: 8 }, { type: "مكية", verses: 11 },
  { type: "مكية", verses: 11 }, { type: "مكية", verses: 8 },  { type: "مكية", verses: 3 },  { type: "مكية", verses: 9 },
  { type: "مكية", verses: 5 },  { type: "مكية", verses: 4 },  { type: "مكية", verses: 7 },  { type: "مكية", verses: 3 },
  { type: "مكية", verses: 6 },  { type: "مدنية", verses: 3 }, { type: "مكية", verses: 5 },  { type: "مكية", verses: 4 },
  { type: "مكية", verses: 5 },  { type: "مكية", verses: 6 }
];