import { v4 as uuidv4 } from 'uuid'
export const cities = [
  { id: uuidv4(), name: "القاهرة", value: "Cairo" },
  { id: uuidv4(), name: "الإسكندرية", value: "Alexandria" },
  { id: uuidv4(), name: "الجيزة", value: "Giza" },
  { id: uuidv4(), name: "القليوبية", value: "Qalyubia" },
  { id: uuidv4(), name: "المنوفية", value: "Monufia" },
  { id: uuidv4(), name: "الغربية", value: "Gharbia" },
  { id: uuidv4(), name: "الدقهلية", value: "Mansoura" },
  { id: uuidv4(), name: "الشرقية", value: "Sharqia" },
  { id: uuidv4(), name: "دمياط", value: "Damietta" },
  { id: uuidv4(), name: "كفر الشيخ", value: "Kafr El Sheikh" },
  { id: uuidv4(), name: "البحيرة", value: "Beheira" },
  { id: uuidv4(), name: "الإسماعيلية", value: "Ismaillia" },
  { id: uuidv4(), name: "بورسعيد", value: "Port Said" },
  { id: uuidv4(), name: "السويس", value: "Suez" },
  { id: uuidv4(), name: "الفيوم", value: "Fayoum" },
  { id: uuidv4(), name: "بني سويف", value: "Beni Suef" },
  { id: uuidv4(), name: "المنيا", value: "Minya" },
  { id: uuidv4(), name: "أسيوط", value: "Asyut" },
  { id: uuidv4(), name: "سوهاج", value: "Sohag" },
  { id: uuidv4(), name: "قنا", value: "Qena" },
  { id: uuidv4(), name: "الأقصر", value: "Luxor" },
  { id: uuidv4(), name: "أسوان", value: "Aswan" },
  { id: uuidv4(), name: "البحر الأحمر", value: "Red Sea" },
  { id: uuidv4(), name: "الوادي الجديد", value: "New Valley" },
  { id: uuidv4(), name: "مطروح", value: "Matrouh" },
  { id: uuidv4(), name: "شمال سيناء", value: "North Sinai" },
  { id: uuidv4(), name: "جنوب سيناء", value: "South Sinai" }
]
