// Countries.js
import { v4 as uuidv4 } from 'uuid';

export const Countries = [
  // --- الدول العربية والإسلامية ---
  { id: uuidv4(), name: "مصر", value: "EG", capital: "Cairo" },
  { id: uuidv4(), name: "المملكة العربية السعودية", value: "SA", capital: "Riyadh" },
  { id: uuidv4(), name: "الإمارات العربية المتحدة", value: "AE", capital: "Abu Dhabi" },
  { id: uuidv4(), name: "الكويت", value: "KW", capital: "Kuwait City" },
  { id: uuidv4(), name: "قطر", value: "QA", capital: "Doha" },
  { id: uuidv4(), name: "البحرين", value: "BH", capital: "Manama" },
  { id: uuidv4(), name: "سلطنة عمان", value: "OM", capital: "Muscat" },
  { id: uuidv4(), name: "الأردن", value: "JO", capital: "Amman" },
  { id: uuidv4(), name: "فلسطين", value: "PS", capital: "Jerusalem" },
  { id: uuidv4(), name: "لبنان", value: "LB", capital: "Beirut" },
  { id: uuidv4(), name: "سوريا", value: "SY", capital: "Damascus" },
  { id: uuidv4(), name: "العراق", value: "IQ", capital: "Baghdad" },
  { id: uuidv4(), name: "اليمن", value: "YE", capital: "Sanaa" },
  { id: uuidv4(), name: "المغرب", value: "MA", capital: "Rabat" },
  { id: uuidv4(), name: "الجزائر", value: "DZ", capital: "Algiers" },
  { id: uuidv4(), name: "تونس", value: "TN", capital: "Tunis" },
  { id: uuidv4(), name: "ليبيا", value: "LY", capital: "Tripoli" },
  { id: uuidv4(), name: "السودان", value: "SD", capital: "Khartoum" },
  { id: uuidv4(), name: "موريتانيا", value: "MR", capital: "Nouakchott" },
  { id: uuidv4(), name: "الصومال", value: "SO", capital: "Mogadishu" },
  { id: uuidv4(), name: "جيبوتي", value: "DJ", capital: "Djibouti" },
  { id: uuidv4(), name: "جزر القمر", value: "KM", capital: "Moroni" },
  { id: uuidv4(), name: "تركيا", value: "TR", capital: "Ankara" },
  { id: uuidv4(), name: "إندونيسيا", value: "ID", capital: "Jakarta" },
  { id: uuidv4(), name: "ماليزيا", value: "MY", capital: "Kuala Lumpur" },
  { id: uuidv4(), name: "باكستان", value: "PK", capital: "Islamabad" },
  { id: uuidv4(), name: "بنجلاديش", value: "BD", capital: "Dhaka" },
  { id: uuidv4(), name: "أفغانستان", value: "AF", capital: "Kabul" },
  { id: uuidv4(), name: "أذربيجان", value: "AZ", capital: "Baku" },
  { id: uuidv4(), name: "أوزبكستان", value: "UZ", capital: "Tashkent" },
  { id: uuidv4(), name: "تركمانستان", value: "TM", capital: "Ashgabat" },
  { id: uuidv4(), name: "طاجيكستان", value: "TJ", capital: "Dushanbe" },
  { id: uuidv4(), name: "قيرغيزستان", value: "KG", capital: "Bishkek" },
  { id: uuidv4(), name: "كازاخستان", value: "KZ", capital: "Astana" },
  { id: uuidv4(), name: "إران", value: "IR", capital: "Tehran" },

  // --- قارة آسيا ---
  { id: uuidv4(), name: "اليابان", value: "JP", capital: "Tokyo" },
  { id: uuidv4(), name: "الصين", value: "CN", capital: "Beijing" },
  { id: uuidv4(), name: "كوريا الجنوبية", value: "KR", capital: "Seoul" },
  { id: uuidv4(), name: "الهند", value: "IN", capital: "New Delhi" },
  { id: uuidv4(), name: "الفلبين", value: "PH", capital: "Manila" },
  { id: uuidv4(), name: "تايلاند", value: "TH", capital: "Bangkok" },
  { id: uuidv4(), name: "فيتنام", value: "VN", capital: "Hanoi" },
  { id: uuidv4(), name: "سنغافورة", value: "SG", capital: "Singapore" },
  { id: uuidv4(), name: "تايوان", value: "TW", capital: "Taipei" },
  { id: uuidv4(), name: "هونج كونج", value: "HK", capital: "Hong Kong" },
  { id: uuidv4(), name: "سريلانكا", value: "LK", capital: "Colombo" },
  { id: uuidv4(), name: "نيبال", value: "NP", capital: "Kathmandu" },
  { id: uuidv4(), name: "ميانمار (بورما)", value: "MM", capital: "Naypyidaw" },
  { id: uuidv4(), name: "كمبوديا", value: "KH", capital: "Phnom Penh" },
  { id: uuidv4(), name: "لاوس", value: "LA", capital: "Vientiane" },
  { id: uuidv4(), name: "جزر المالديف", value: "MV", capital: "Male" },
  { id: uuidv4(), name: "بروناي", value: "BN", capital: "Bandar Seri Begawan" },

  // --- قارة أوروبا ---
  { id: uuidv4(), name: "المملكة المتحدة (بريطانيا)", value: "GB", capital: "London" },
  { id: uuidv4(), name: "فرنسا", value: "FR", capital: "Paris" },
  { id: uuidv4(), name: "ألمانيا", value: "DE", capital: "Berlin" },
  { id: uuidv4(), name: "إيطاليا", value: "IT", capital: "Rome" },
  { id: uuidv4(), name: "إسبانيا", value: "ES", capital: "Madrid" },
  { id: uuidv4(), name: "البرتغال", value: "PT", capital: "Lisbon" },
  { id: uuidv4(), name: "روسيا", value: "RU", capital: "Moscow" },
  { id: uuidv4(), name: "هولندا", value: "NL", capital: "Amsterdam" },
  { id: uuidv4(), name: "بلجيكا", value: "BE", capital: "Brussels" },
  { id: uuidv4(), name: "سويسرا", value: "CH", capital: "Bern" },
  { id: uuidv4(), name: "النمسا", value: "AT", capital: "Vienna" },
  { id: uuidv4(), name: "اليونان", value: "GR", capital: "Athens" },
  { id: uuidv4(), name: "السويد", value: "SE", capital: "Stockholm" },
  { id: uuidv4(), name: "النرويج", value: "NO", capital: "Oslo" },
  { id: uuidv4(), name: "الدنمارك", value: "DK", capital: "Copenhagen" },
  { id: uuidv4(), name: "فنلندا", value: "FI", capital: "Helsinki" },
  { id: uuidv4(), name: "أيرلندا", value: "IE", capital: "Dublin" },
  { id: uuidv4(), name: "بولندا", value: "PL", capital: "Warsaw" },
  { id: uuidv4(), name: "أوكرانيا", value: "UA", capital: "Kyiv" },
  { id: uuidv4(), name: "رومانيا", value: "RO", capital: "Bucharest" },
  { id: uuidv4(), name: "جمهورية التشيك", value: "CZ", capital: "Prague" },
  { id: uuidv4(), name: "المجر (هنغاريا)", value: "HU", capital: "Budapest" },
  { id: uuidv4(), name: "بلغاريا", value: "BG", capital: "Sofia" },
  { id: uuidv4(), name: "كرواتيا", value: "HR", capital: "Zagreb" },
  { id: uuidv4(), name: "صربيا", value: "RS", capital: "Belgrade" },
  { id: uuidv4(), name: "سلوفاكيا", value: "SK", capital: "Bratislava" },
  { id: uuidv4(), name: "سلوفينيا", value: "SI", capital: "Ljubljana" },
  { id: uuidv4(), name: "ليتوانيا", value: "LT", capital: "Vilnius" },
  { id: uuidv4(), name: "لاتفيا", value: "LV", capital: "Riga" },
  { id: uuidv4(), name: "إستونيا", value: "EE", capital: "Tallinn" },
  { id: uuidv4(), name: "ألبانيا", value: "AL", capital: "Tirana" },
  { id: uuidv4(), name: "البوسنة والهرسك", value: "BA", capital: "Sarajevo" },
  { id: uuidv4(), name: "قبرص", value: "CY", capital: "Nicosia" },
  { id: uuidv4(), name: "أيسلندا", value: "IS", capital: "Reykjavik" },
  { id: uuidv4(), name: "مالطا", value: "MT", capital: "Valletta" },
  { id: uuidv4(), name: "مقدونيا الشمالية", value: "MK", capital: "Skopje" },
  { id: uuidv4(), name: "جورجيا", value: "GE", capital: "Tbilisi" },
  { id: uuidv4(), name: "أرمينيا", value: "AM", capital: "Yerevan" },

  // --- أمريكا الشمالية والوسطى ---
  { id: uuidv4(), name: "الولايات المتحدة الأمريكية", value: "US", capital: "Washington D.C." },
  { id: uuidv4(), name: "كندا", value: "CA", capital: "Ottawa" },
  { id: uuidv4(), name: "المكسيك", value: "MX", capital: "Mexico City" },
  { id: uuidv4(), name: "كوبا", value: "CU", capital: "Havana" },
  { id: uuidv4(), name: "جامايكا", value: "JM", capital: "Kingston" },
  { id: uuidv4(), name: "جمهورية الدومينيكان", value: "DO", capital: "Santo Domingo" },
  { id: uuidv4(), name: "بورتوريكو", value: "PR", capital: "San Juan" },
  { id: uuidv4(), name: "كوستاريكا", value: "CR", capital: "San Jose" },
  { id: uuidv4(), name: "بنما", value: "PA", capital: "Panama City" },
  { id: uuidv4(), name: "غواتيمالا", value: "GT", capital: "Guatemala City" },
  { id: uuidv4(), name: "هندوراس", value: "HN", capital: "Tegucigalpa" },
  { id: uuidv4(), name: "السلفادور", value: "SV", capital: "San Salvador" },
  { id: uuidv4(), name: "نيكاراجوا", value: "NI", capital: "Managua" },

  // --- أمريكا الجنوبية ---
  { id: uuidv4(), name: "البرازيل", value: "BR", capital: "Brasilia" },
  { id: uuidv4(), name: "الأرجنتين", value: "AR", capital: "Buenos Aires" },
  { id: uuidv4(), name: "كولومبيا", value: "CO", capital: "Bogota" },
  { id: uuidv4(), name: "تشيلي", value: "CL", capital: "Santiago" },
  { id: uuidv4(), name: "بيرو", value: "PE", capital: "Lima" },
  { id: uuidv4(), name: "فنزويلا", value: "VE", capital: "Caracas" },
  { id: uuidv4(), name: "الإكوادور", value: "EC", capital: "Quito" },
  { id: uuidv4(), name: "بوليفيا", value: "BO", capital: "Sucre" },
  { id: uuidv4(), name: "باراجواي", value: "PY", capital: "Asuncion" },
  { id: uuidv4(), name: "أوروغواي", value: "UY", capital: "Montevideo" },

  // --- قارة أفريقيا ---
  { id: uuidv4(), name: "موزمبيق", value: "MZ", capital: "Maputo" },
  { id: uuidv4(), name: "نيجيريا", value: "NG", capital: "Abuja" },
  { id: uuidv4(), name: "جنوب أفريقيا", value: "ZA", capital: "Pretoria" },
  { id: uuidv4(), name: "كينيا", value: "KE", capital: "Nairobi" },
  { id: uuidv4(), name: "غانا", value: "GH", capital: "Accra" },
  { id: uuidv4(), name: "إثيوبيا", value: "ET", capital: "Addis Ababa" },
  { id: uuidv4(), name: "أوغندا", value: "UG", capital: "Kampala" },
  { id: uuidv4(), name: "تنزانيا", value: "TZ", capital: "Dodoma" },
  { id: uuidv4(), name: "السنغال", value: "SN", capital: "Dakar" },
  { id: uuidv4(), name: "كوت ديفوار (ساحل العاج)", value: "CI", capital: "Yamoussoukro" },
  { id: uuidv4(), name: "الكاميرون", value: "CM", capital: "Yaounde" },
  { id: uuidv4(), name: "أنغولا", value: "AO", capital: "Luanda" },
  { id: uuidv4(), name: "زيمبابوي", value: "ZW", capital: "Harare" },
  { id: uuidv4(), name: "زامبيا", value: "ZM", capital: "Lusaka" },
  { id: uuidv4(), name: "مدغشقر", value: "MG", capital: "Antananarivo" },
  { id: uuidv4(), name: "مالي", value: "ML", capital: "Bamako" },
  { id: uuidv4(), name: "غينيا", value: "GN", capital: "Conakry" },
  { id: uuidv4(), name: "النيجر", value: "NE", capital: "Niamey" },
  { id: uuidv4(), name: "بوركينا فاسو", value: "BF", capital: "Ouagadougou" },
  { id: uuidv4(), name: "تشاد", value: "TD", capital: "N'Djamena" },
  { id: uuidv4(), name: "رواندا", value: "RW", capital: "Kigali" },
  { id: uuidv4(), name: "موريشيوس", value: "MU", capital: "Port Louis" },

  // --- أوقيانوسيا ---
  { id: uuidv4(), name: "أستراليا", value: "AU", capital: "Canberra" },
  { id: uuidv4(), name: "نيوزيلندا", value: "NZ", capital: "Wellington" },
  { id: uuidv4(), name: "فيجي", value: "FJ", capital: "Suva" },
  { id: uuidv4(), name: "بابوا غينيا الجديدة", value: "PG", capital: "Port Moresby" }
];